[build]
  command = "npm run build"
  publish = "dist/public"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  VITE_SUPABASE_URL = "https://lmitonmckoomqcorgnkj.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtaXRvbm1ja29vbXFjb3JnbmtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDEzMTAsImV4cCI6MjA2NjQxNzMxMH0.GE1wi7cjCcuf2ZlT9gsxEUR2G7pkkabsCZwRQOJ8Gdo"

[[redirects]]
  from = "/api/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 